update [2]
TheRouletteBoi/rdr-nativedb-data pull request #22
Opened 2024-12-12 10:41 UTC by PliskinDev

2024-12-15 06:22 UTC, TheRouletteBoi requested changes
Please see my comments and make changes.

2024-12-15 06:22 UTC, TheRouletteBoi commented on schema.json
> +				"Weapon", "Weapon*"
Weapon Type should not to a type in native.h. Keep as int

2024-12-15 06:22 UTC, TheRouletteBoi commented on schema.json
> +				"Faction", "Faction*",
Remove Faction type and use int. These are not common enough to be made a type.

2024-12-15 06:22 UTC, TheRouletteBoi commented on schema.json
> +				"Journal", "Journal*",
For `Journal` you can use `JournalHandle` because it can be used for a class name. Too common to be using Journal

2024-12-15 20:39 UTC, PliskinDev commented
done

2024-12-18 07:09 UTC, TheRouletteBoi commented
> done

json failed validation. Please fix the typo

2024-12-18 08:04 UTC, PliskinDev commented
fixed

2024-12-18 08:07 UTC, PliskinDev commented
> > done
> 
> json failed validation. Please fix the typo

fixed

2024-12-18 18:58 UTC, merged